project:
  type: website

website:
  title: "MatesCCSS"
  favicon: "/favicon.ico"
  page-footer:
    center: "Aquesta web pertany a [Naïm Saadi](https://nsaadig16.github.io) i és d'ús exclusiu dels alumnes de l'Acadèmia Gauss."
    border: true
  navbar:
    logo: "/favicon.ico"
    pinned: true
    left:
      - href: index.qmd
        text: Inici
      - href: contents/sistemes.qmd
        text: Sistemes d'equacions
      - text: Probabilitat
        menu:
          - href: probabilitat_bayesiana.qmd
            text: Probabilitat bayesiana
format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true



